### ISSUE TITLE
setting unique on Meteor.users fields still allows duplicates

### ISSUE THREAD

**Issue by chrisbutler** [aldeed/meteor-collection2#125]
with the following code (this isn't the full schema, just for the sake of example):
```
userSchema = new SimpleSchema({
  uuid: {
    type: String,
    index: true,
    unique: true
  }
});

Meteor.users.attachSchema(userSchema);
```
I'm still able to insert a user with the same uuid as an existing user. Am I missing something?

**Comment by aldeed** [comment]
@ernestorocha, while this can be confusing, there is actually no bug here. Setting `index` to anything other than `false` creates the mongo index. If you then make changes to that index, such as trying to change it to be a unique index, mongo will ignore because you already have an index. Setting `index` to `false` triggers a drop, at which time you could then recreate the index as a unique index.

So the correct way to do your example is:

```js
Uniques = new Meteor.Collection("uniques");

hash = {
  code: {
    type: String,
    index: true,
    unique: false 
  }
};

Schema = new SimpleSchema(hash);
Uniques.attachSchema(Schema);

hash.code.index = false;

Schema = new SimpleSchema(hash);
Uniques.attachSchema(Schema);

hash.code.index = true;
hash.code.unique = true;

Schema = new SimpleSchema(hash);
Uniques.attachSchema(Schema);
```

Eventually I think the indexing features can be improved, but not until Meteor supports later versions of mongo.

**Comment by christiangenco** [comment]
Oh man, this is a pretty big gotcha. Would you be open to adding a blurb about this in the README?

**Comment by aldeed** [comment]
I clarified the readme.

**Comment by jedwards1211** [comment]
*MongoDB can't guarantee the uniqueness of secondary keys across shards anyway*.  Does Meteor even do anything to mitigate the potential of duplicate usernames?
