### ISSUE TITLE
Validating fields which dont have to be inserted

### ISSUE THREAD

**Issue by dpacmittal** [aldeed/meteor-collection2#180]
I am not sure if this relates to collection2 or simpleschema, but there's a need for another rule which makes a key skip database insertion. One example of such a field is Confirm password field which is only required for validation but is not to be inserted in the database.

Something like 'skipInsert' or 'validationOnly'.

**Comment by aldeed** [comment]
In autoform, you can use a form schema that contains the extra fields, and then remove them in a before insert hook. I don't think it's worth adding the extra options to autoform since it's really pretty easy to do it yourself in the before hook, but feel free to make a case for it.

It doesn't make sense in SS pkg because there is no "insert" concept outside of a database context. It could go in collection2, but it doesn't feel right to include a field in a collection schema if you don't actually want that field in your collection.
