### ISSUE TITLE
Is it possible to attach a schema to a subset of user's collection?

### ISSUE THREAD

**Issue by AlexFrazer** [aldeed/meteor-collection2#208]
Here's what I am trying to do.

```
var UserBase = {
  emails: {
    type: [Object],
    optional: true
  },
  emails: {
    type: [Object],
    optional: true
  },
  "emails.$.address": {
    type: String,
    regEx: SimpleSchema.RegEx.Email
  },
  "emails.$.verified": {
    type: Boolean,
    defaultValue: function () {
      return false;
    }
  },
  createdAt: {
    type: Date
  }
}

AdminUserSchema = new SimpleSchema(_.extend(UserBase, {
  profile: {
    type: AdminProfileSchema
  },
  settings: {
    type: AdminSettingsSchema
  },
}));

PlayerUserSchema = new SimpleSchema(_.extend(UserBase, {
  profile: {
    type: PlayerProfileSchema
  },
  settings: {
    type: PlayerSettingsSchema
  }
}))

Meteor.users.attachSchema(AdminUserSchema, { role: "admin" });
Meteor.users.attachSchema(PlayerUserSchema, { role: "player" });
```

So essentially, I would creating a type of user. Is there a proper way to do this with collection2? I might be thinking of it wrong.

**Comment by nelisbijl** [comment]
I'm also interested in supporting subclasses. The well known Animal, Dog, Cat, Monkey all stored in one collection 'animals'

**Comment by carrot93** [comment]
When I try to use Meteor.users.attach Schema.profile, I met the meteor user-status confliction. It needs 
I must define Schemas.status:
online
lastLogin
lastLogin.$.date
lastLogin.$.ipAddr
lastLogin.$.userAgent
idle
lastActivity

but the subclasses not allowed by simple-schema. Any fun idea?

**Comment by aldeed** [comment]
I don't have plans to support this. The best you could do is include the full set of properties, and then any that are not in both roles should be optional with custom validation function to determine if they should be required for the current user.

**Comment by j20** [comment]
Was looking for this too. This would be an incredible enhancement. E.g. `Products` collection with `type: 'a', type: 'b', type: 'c'`.

The difficulty right now is that having one schema for all types in that collections causes conflicts. For instance, if you have a property of the same name (e.g. query) but that needs to be handled differently (e.g. using different autovalue, etc).

Having separate schemas would also allow passing an individual schema to an autoform instance, for better organization and to allow marking more fields as `required` since there wouldn't be conflicts between the schemas for each subtype.
