### ISSUE TITLE
collection-hooks: Bypass all validation and hooks

### ISSUE THREAD

**Issue by theduke** [aldeed/meteor-collection2#224]
I'm using Collection2 with https://github.com/matb33/meteor-collection-hooks and I'm trying to figure out a  way to bypass both Collection2 validation and the hooks.

When using ```MyCollection._collection.insert()``` the hooks fire.
When using ```MyCollection.direct.insert()``` the Collection2 validation runs.

Any ideas for this?
(As a workaround I resorted to using MyCollection.rawCollection())

**Comment by serkandurusoy** [comment]
Use the following syntax:

    myCollection.insert(doc, {validate: false});

for inserts that are not validated as described here: https://github.com/aldeed/meteor-collection2#inserting-or-updating-without-validating

And since `direct.insert` bypasses, hooks, you can combine the two to achieve your requirement

    MyCollection.direct.insert(doc, {validate: false})

The hooks package must be declared *after* collection2 in your packages file.
