### ISSUE TITLE
Mutliple types for the same field

### ISSUE THREAD

**Issue by justindra** [aldeed/meteor-collection2#264]
Hi,

So I have a collection of say items. And the item has a certain type. And this type would define what another field contains.

For example,
````javascript
Item1 = {
    type: 'cd-audio',
    content: [{songName: 'sds', songNo: 1}, ..., {songName: 'some other name', songNo: 2}]
};
Item2 = {
    type: 'sign',
    content: ['hello', ..., 'some other sign']
};
````

So the content for when the type is CD, it is an array of objects where as when the type is sign, it is an array of strings. Just wondering what would be the best way to do this in SimpleSchema or if it is even possible?

I tried the blackbox option but that does not seem to work for an Array.

Cheers!

**Comment by aldeed** [comment]
It is not possible unless you dynamically adjust the entire schema that you've attached, which I don't recommend. In general you lose some flexibility when attaching a schema. In this case a simple solution might be to do

```js
content: { type: Array }
'content.$': { type: Object, blackbox: true }
```

And then instead of an array of strings, do `content: [{name: 'hello'}, {name: 'some other sign'}]` for the `sign` type.
