### ISSUE TITLE
Disable validations without performance impact

### ISSUE THREAD

**Issue by stephanvane** [aldeed/meteor-collection2#288]
Inserting a (large) document with `{ validate: false, filter: false, autoConvert: false, removeEmptyStrings: false, getAutoValues: false }` takes just as long as without those options.

- an insert *with* an attached schema and validations *enabled* takes +- 45 sec
- an insert *with* an attached schema and validations *disabled* takes +- 45 sec
- an insert *without* an attached schema takes around 0.1 sec

So removing the `attachSchema` call altogether speeds things up (from 45 to 0.1 sec), but this removes all possibilities for validation (on updates etc.).

Any thoughts about this? What is the code doing during those 45 seconds?

**Comment by aldeed** [comment]
I think it is because it parses the whole object regardless (though it must be a REALLY big object to take 45 secs).

The next major release of simple-schema will have some performance improvements. I will see about maybe figuring out a way to parse only what we need to validate. But beyond that, collection2 can probably offer an option that completely skips all cleaning code (`clean: false`)

**Comment by aldeed** [comment]
I release 2.6.0 with a new `bypassCollection2` option.

**Comment by stephanvane** [comment]
Hi,
It was a big object, but not enormous (few hundred nested small objects).

A `bypassCollection2` option would be great. I could insert the large object with trusted data (not validated by collection2) on the server side, and use the validation when updating the object with untrusted data.

Thanks a lot for having a look at this!
