### ISSUE TITLE
Provide ability to specify default values for options at the collection level

### ISSUE THREAD

**Issue by Ragsboss** [aldeed/meteor-collection2#299]
Cleaning data, especially the 'filtering' out of unknown keys, by default, can surprise people, as they may assume all the keys they are inserting are going into Mongo.

Could we add the ability, at attachSchema time, to specify defaults for all options in https://github.com/aldeed/meteor-simple-schema#cleaning-data...

**Comment by rhlsthrm** [comment]
+1

**Comment by BudgieInWA** [comment]
I think this is quite important. I've never wanted to silently filter fields and it continues to catch me out time and time again, despite knowing of, and understanding, the filtering behaviour.

**Comment by eric-burel** [comment]
Hi, 
I confirm this functionnality would be great. For example, when you want to disable `filter`, most of the time its because your collection is meant to contain unvalidated keys, for example because it contains documents with various shapes.
 So obviously those unvalidated keys will appear everywhere and you will have to set `filter` to `false` on every `insert`, `update` and `upsert`.

To be more precise, I think default options should be set up in way similar to this: 
```
MyCollection.attachSchema(mySchema, {...} , {
    insert : {filter:false},
   update : {filter:false},
   upsertOnInsert : {filter:false},
   upsertOnUpdate : {filter:false},
}
```

I'll try to PR, if I have a few minutes ahead of me :)

**Comment by aldeed** [comment]
Closing this since you can [set defaults on the schema that you're attaching](https://github.com/aldeed/simple-schema-js#set-default-cleaning-options) now, and there is another issue (https://github.com/aldeed/meteor-collection2/issues/372) for overrides per operation type.
