### ISSUE TITLE
Attaching Multiple Schemas to the Meteor.users Collection

### ISSUE THREAD

**Issue by mjgallag** [aldeed/meteor-collection2#310]
@aldeed this new feature is awesome, and you added at the exact moment I realized I needed it! :smile:

Unfortunately, it appears that when the selector is not passed with an update, the database is not queried to get the current value of the selector. I realize this is probably a known limitation, but I'm not sure how to use this feature with Meteor.users without this functionality as I can't easily change internal Meteor.users update calls to include the selector. Any ideas?

Thanks!

```
Meteor.users.attachSchema(new SimpleSchema([meteor, user, member]), { selector: { type: 'member' } });
Meteor.users.attachSchema(new SimpleSchema([meteor, user, employer]), { selector: { type: 'employer' } });
```

`Cannot call method 'namedContext' of null at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:232:1)`

**Comment by mjgallag** [comment]
FYI @aldeed I've worked around this for now by not using Collection2 on Meteor.users, dropping back to SimpleSchema:
```
Accounts.validateNewUser(function (user) {
  if (user.type === 'member')
    User.meteor.member.validate(user);
  else if (user.type === 'employer')
    User.meteor.employer.validate(user);
  else
    return false;

  return true;
});
```

@aldeed do you have plans to extend this new Collection2 multiple schema by selector feature to AutoForm?

Thanks again!

**Comment by artjomg** [comment]
+1

**Comment by odesey** [comment]
Any updates on a possible solution for this? I am having the same error for the Users collection with meteor 1.3.

**Comment by bharathkeshav12** [comment]
Would you please show me how you're implementing` { selector: { type: 'member' }`  and `{ selector: { type: 'employer' } } `? 

As of now, I'm getting an error saying that a argument to `doc` must be passed.

Thanks

**Comment by tomasz-nolberczak** [comment]
It is impossible to assign multiple schemas to Meteor.users collection. I can't do that, tried in dozens of times.

These are my schemas: 

```
UsersSchema = new SimpleSchema({
    username: {
        type: String,
        optional: true
    },
    emails: {
        type: Array,
        optional: true
    },
    "emails.$": {
        type: Object
    },
    "emails.$.address": {
        type: String,
        regEx: SimpleSchema.RegEx.Email
    },
    "emails.$.verified": {
        type: Boolean
    },
    createdAt: {
        type: Date
    },
    services: {
        type: Object,
        optional: true,
        blackbox: true
    },
    profile: {
        type: Object,
        optional: true,
    },
    'profile.role': {
        type: String,
        allowedValues: ['admin', 'owner', 'client']
    },
    heartbeat: {
        type: Date,
        optional: true
    }
});

OwnersSchema = new SimpleSchema([UsersSchema, {
    'profile.user': {
        type: Object,
        optional: true,
    },
    'profile.user.firstName': {
        type: String,
        optional: true,
    },
    'profile.user.lastName': {
        type: String,
        optional: true,
    },
    'profile.user.position': {
        type: String,
        optional: true,
    },
    'profile.company': {
        type: Object,
        optional: true,
    },
    'profile.company.name': {
        type: String,
        optional: true,
    },
    'profile.company.address': {
        type: String,
        optional: true,
    },
    'profile.company.NIP': {
        type: String,
        optional: true,
    },
}]);

ClientsSchema = new SimpleSchema([UsersSchema, {
    'profile.phone': {
        type: Number
    },  
    'profile.createdAt': {
        type: Date,
        defaultValue: new Date(),
    },
    'profile.ownerID': {
        type: String,
    },
    'profile.packages': {
        type: [String],
        optional: true,
    },
    'profile.active': {
        type: Boolean,
        defaultValue: false
    }
}]);

Meteor.users.attachSchema(OwnersSchema, { selector: { 'role': 'owner' } });
Meteor.users.attachSchema(ClientsSchema, { selector: { 'role': 'client' } });
```

This is error I'm keep getting: 

```
Exception while invoking method 'ownerRegister' TypeError: Cannot read property 'namedContext' of null
at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:262:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:173:1)
at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1257:25)
at _createUser (packages/accounts-password/password_server.js:998:25)
at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1067:10)
at [object Object].ownerRegister (imports/server/methods/owners.js:16:12)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
at packages/ddp-server/livedata_server.js:711:19
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at packages/ddp-server/livedata_server.js:709:40
```

It breaks up on Accounts.createUser method.

```
Accounts.createUser({
			username: params.login,
			email: params.email,
			password: params.password,
			profile: {
				role: 'owner',
				user: {
					firstName: '',
					lastName: '',
					position: '',
				},
				company: {
					name: params.companyName,
					address: params.companyAddress,
					NIP: params.companyNIP,
				}
			}
		});
```

@aldeed, can you help me somehow, please? I would be very grateful!

**Comment by odesey** [comment]
Any updates on this issue?

**Comment by bduff9** [comment]
@aldeed A year later and no word on this?  I too am running into this exact issue now and have no way around it but to relax my schema restrictions, which means it is now possible for bad data to get into my User collection.  Do we know what the actual issue is here specific to the User collection or is this an issue with every single collection where you assign more than one schema?

**Comment by aldeed** [comment]
@bduff9 I'm not sure there is really a solution to this. I'm not going to have it query the database for the selector because that could open up a can of worms. I don't personally understand why this is much of a problem. You can just make a bunch of the fields optional in the attached schema if certain roles don't need them, and then validate each profile object on your own against the more strict schema before you insert/update it.

Will close pending any better ideas from the community

**Comment by bduff9** [comment]
@aldeed I see.  While disappointing, it is nice to at least hear some info regarding this issue.  My specific case is more to the one reported by @tomasz-nolberczak where you cannot assign multiple schemas to the user schema at all (not related to on update where something isn't passed which I agree can be worked around by just passing the value).

In this case, it is an issue as I need to have a field be optional _only_ on create, and never after that.  If I just make it optional all the time, it is possible for bad data to get in there.  Yes, it can be handled manually, but so can every single other field to where I wouldn't need collection2 at all.  However, that relies on every case of accessing the db being absolutely correct, and is the reason why collection2 is so great, because if I or another developer forget that the field is required, the "db" will let us know.

Otherwise, there's not much that can be worked around here as the Accounts package is the one doing the inserting, not me so I can either make the field always optional and hope for the best, or ask for this to be looked into.  I'm not sure that in this specific case, the db would need to be queried as the object has the required info, it just fails when more than one schema is attached (for every action, not just update).

I do see now that the original issue reported is a bit different, however the comment I replied to is the same problem I am having (which is where Google dropped me when I searched for it).  If this requires a new issue to be opened, I would be happy to do so but I want to ensure you see what I and @tomasz-nolberczak  are reporting which is a bit different than the OP.  Thanks!

**Comment by aldeed** [comment]
@bduff9 If you can create a repo that has a simple app showing what you are trying to do and how it is not working, and open a new issue, that will make it easier for me or someone to investigate. Please make sure you are using latest `aldeed:collection2` Meteor package and latest `simpl-schema` NPM package when reproducing.
