### ISSUE TITLE
attachSchema broken since meteor 1.4.2 update

### ISSUE THREAD

**Issue by neurosoup** [aldeed/meteor-collection2#353]
Since the 1.4.2 meteor update the attachSchema function leads to this error : 

allow-deny.js:477Uncaught TypeError: Cannot read property 'insert' of undefined

![image](https://cloud.githubusercontent.com/assets/319286/19716561/b9f8528e-9b5c-11e6-8866-1d4b3e5f2364.png)

Here is the code calling the attachSchema function : 
const Clusters = new ClustersCollection('clusters')
Clusters.attachSchema(Schemas.Clusters)

The cluster collection extends a CollectionBase class wich is defined as follow

`
export default class CollectionBase extends Mongo.Collection {

  constructor(collectionName) {
    super(collectionName)               
  }

  beforeInsert(doc) {  }

  afterInsert(doc) {  }

  beforeUpdate(selector, modifier, options) {  }

  afterUpdate(selector, modifier, options) {  }

  update(selector, modifier, options, callback) {    
    try {
      this.beforeUpdate(selector, modifier, options)      
      const res = super.update(selector, modifier, options, callback)
      if (res.insertedId) {
        const doc = super.findOne(res.insertedId)
        this.afterInsert(doc)
      } else {
        this.afterUpdate(selector, modifier, options)
      }
      return res
    } catch (e) {
      Logger.error(e)
      throw e
    }
  }

  insert(doc, callback) {
    try {
      this._c2._simpleSchema.clean(doc)
      this.beforeInsert(doc)
      const res = super.insert(doc, callback)
      doc._id = res
      this.afterInsert(doc)
      return doc._id
    } catch (e) {
      Logger.error(e)
      throw e
    }
  }

}`

I'm trying to investigate further.

Thanks

**Comment by neurosoup** [comment]
Sorry, 

seems to be a Mongo.Collection inheritance problem. Something has changed since the meteor 1.4.2 and I can't extends from Mongo.Collection like before.

I Close the issue.

**Comment by domq** [comment]
For the benefit of the next person to wind up here by searching the error message: in my case, the issue was that my `SimpleSchema` was the one out of [`aldeed:simple-schema`](https://github.com/aldeed/meteor-simple-schema), as opposed to the one out of [`simpl-schema`](https://www.npmjs.com/package/simpl-schema) as it should.

Here is what I did to fix the symptom:

- searched for all occurences of `SimpleSchema` in my source code
- made sure that each of them was preceded by <pre>import SimpleSchema from "simpl-schema";</pre>
- removed all occurences of <pre><s>import { SimpleSchema } from 'meteor/aldeed:simple-schema';</s></pre>
